# Generated by Django 3.2 on 2022-05-15 15:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/logo_1080_1080.png', null=True, upload_to=users.models.get_profile_image_path),
        ),
    ]
